name: Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  K8S_CONTAINER: sertxudev
  K8S_DEPLOYMENT: sertxudev
  K8S_NAMESPACE: sertxudev

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  build-and-deploy:
    needs: tests
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v6

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ github.repository }}:buildcache
          cache-to: type=registry,ref=${{ github.repository }}:buildcache,mode=max

      - name: Deploy new image
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.KUBERNETES_MASTER_SSH_HOST }}
          username: ${{ secrets.KUBERNETES_MASTER_SSH_USER }}
          port: ${{ secrets.KUBERNETES_MASTER_SSH_PORT }}
          key: ${{ secrets.KUBERNETES_MASTER_SSH_KEY }}
          script: |
            microk8s kubectl set image deployment/${{ env.K8S_DEPLOYMENT }}-app -n ${{ env.K8S_NAMESPACE }} ${{ env.K8S_CONTAINER }}-app="${{ github.repository }}:sha-${{ github.sha }}"
            microk8s kubectl set image deployment/${{ env.K8S_DEPLOYMENT }}-worker -n ${{ env.K8S_NAMESPACE }} ${{ env.K8S_CONTAINER }}-worker="${{ github.repository }}:sha-${{ github.sha }}"
            microk8s kubectl set image deployment/${{ env.K8S_DEPLOYMENT }}-scheduler -n ${{ env.K8S_NAMESPACE }} ${{ env.K8S_CONTAINER }}-scheduler="${{ github.repository }}:sha-${{ github.sha }}"
